#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=50gb,walltime=10:00:00
#PBS -N app-pyAFQ-segment

mkdir -p wmc wmc/tracts wmc/surfaces

# convert aparc+aseg to nifti
[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

if [ ! -f aparc+aseg.nii.gz ]; then
    echo "converting aparc.a2009+aseg file to nifti"
    singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt \
        docker://brainlife/freesurfer-mini:6.0.1 ./convertaseg.sh
fi

# run AFQ segmentation
if [ ! -f ./wmc/classification.mat ]; then
	time singularity exec -e docker://brainlife/pyafq:0.4.1 ./segment-afq.py
fi

# create surfaces for visualizer
if [ ! -f ./wmc/surfaces/index.json ]; then
	echo "Generating surfaces/ vtk from aparc+aseg.mgz"
	time singularity exec -e docker://brainlife/pythonvtk:1.1 ./freesurfer2vtks.py
fi

if [ -f ./wmc/classification.mat ]; then
	echo "complete"
	exit 0
else
	echo "failed"
	exit 1
fi
